config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'},
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'posts#index'

  resources :users, only: [:index, :show] do
    resources :profiles, only: [:edit, :update]
    member do
      get "edit_name"
      post "update_name"
    end
  end
  resources :friendships, only: [:create, :update, :destroy]
  resources :posts, except: [:show, :new] do
    resources :comments, only: [:create, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  after_create :init_profile, :send_welcome_email

  validates :first_name, :last_name, presence: true

  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :inverse_friends, through: :inverse_friendships, source: :user
  
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one  :profile, dependent: :destroy

  def confirmed_friends
    (friendships.map{ |fs| fs.friend if fs.accepted? } + 
      inverse_friendships.map{ |fs| fs.user if fs.accepted? }).compact
  end

  # users that have SENT a request
  def pending_friends
    inverse_friendships.map{ |fs| fs.user unless fs.accepted? }.compact
  end

  # users that have RECEIVED a request
  def proposed_friends
    friendships.map{ |fs| fs.friend unless fs.accepted? }.compact
  end

  # no friend and no request
  def possible_friends
    ids = (friendships.map{ |fs| fs.friend_id } +
      inverse_friendships.map{ |fs| fs.user_id }).compact
    User.where.not(id: ids) - [self]
  end

  def sort_for_index
    (pending_friends.sort_by(&:last_name) +
      confirmed_friends.sort_by(&:last_name) +
      proposed_friends.sort_by(&:last_name) +
      possible_friends.sort_by(&:last_name))
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def init_profile
    self.create_profile
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name.split[0]
      user.last_name = auth.info.name.split[1..-1].join(' ')
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]

  def index
    @users = current_user.sort_for_index
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.sort_by(&:created_at).reverse
    @post = Post.new
  end

  def edit_name
    @user = User.find(params[:id])
  end

  def update_name
    @user = User.find(params[:id])
    @user.update(name_params)
    flash.notice = 'Name successfully changed.'
    redirect_to user_path(current_user)
  end

  private

  def name_params
    params.require(:user).permit(:first_name, :last_name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_name_form.html.erb
<div id="edit-name">
  <%= form_with model: current_user, url: update_name_user_path(current_user), method: 'post', local: true do |f| %>
    <ul>
      <li class="field">
        <%= f.label :first_name, 'First Name:' %><br>
        <%= f.text_field :first_name %>
      </li>
      
      <li class="field">
        <%= f.label :last_name, 'Last Name:' %><br>
        <%= f.text_field :last_name %>
      </li>
    </ul>

    <%= f.submit 'Submit', class: "submit" %>
  <% end %>
</div>

app/views/users/_profile.html.erb
<div id="profile">
  <% if profile.photo.attached? %>
    <%= image_tag profile.photo, class: "photo" %>
  <% end %>

  <div class="data">
    <ul class="items">
      <li class="item">Birth date: <%= profile.birthdate %></li>
      <li class="item">Gender: <%= profile.sex %></li>
      <li class="item">Location: <%= profile.location %></li>
    </ul>

    <% if current_user == profile.user %>
      <div class="options">
        <%= link_to "Edit profile", [:edit, profile.user, profile], class: "edit" %>
        <%= link_to "Change name", edit_name_user_path(profile.user), class: "name" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit_name.html.erb
<h2>Change your name:</h2>

<%= render partial: 'name_form' %>

app/views/users/index.html.erb
<div id="users_index">
  <h2>Search here for your friends. Or invite new ones...</h2>

  <ul><% @users.each do |user| %>
    <li id="friend">
      <div id="photo-name">
        <div id="photo-div">
          <% if user.profile.photo.attached? %>
            <%= image_tag user.profile.photo, class: "photo" %>
          <% end %>
        </div>
        <%= link_to user.full_name, user_path(user), class: "friend_name" %>
      </div>
      
      <div id="friend-option">
        <% if current_user.pending_friends.include?(user) %>
          <%= link_to "Accept friend request", friendship_path(user, friend_id: user.id), method: :put, class: "option" %>
        <% end %>
        <% if current_user.possible_friends.include?(user) %>
          <%= link_to "Send friend request", friendships_path(friend_id: user.id), method: :post, class: "option" %>
        <% end %>
        <% if current_user.confirmed_friends.include?(user) %>
          <%= link_to "Remove as friend", friendship_path(user, friend_id: user.id), method: :delete, data: {confirm: "Remove this friend?"}, class: "option" %>
        <% end %>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<h2><%= "#{@user.full_name}'s page" %></h2>

<h3>About <%= @user.first_name %></h3>
<%= render partial: 'profile', locals: {profile: @user.profile} %>

<% if current_user.confirmed_friends.include?(@user) || current_user == @user %>
  <h3><%= @user.first_name %>'s posts</h3>

  <% if current_user == @user %>
    <%= render partial: 'posts/form', locals: {post: @post} %>
  <% end %>
  <%= render partial: 'posts/post', collection: @posts %>
<% end %>