config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'},
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'posts#index'

  resources :users, only: [:index, :show] do
    resources :profiles, only: [:edit, :update]
    member do
      get "edit_name"
      post "update_name"
    end
  end
  resources :friendships, only: [:create, :update, :destroy]
  resources :posts, except: [:show, :new] do
    resources :comments, only: [:create, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validate :content_or_photo

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :photo

  def content_or_photo
    unless content.present? || photo.attached?
      errors.add(:content, "post can't be blank")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = (current_user.posts +
      current_user.confirmed_friends.map{ |f| f.posts }.flatten)
      .sort_by(&:created_at).reverse
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.save
    flash.notice = 'Post created'
    redirect_back(fallback_location: root_path)
  end

  def edit
    session[:return_to] ||= request.referer
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    flash.notice = 'Post updated'
    redirect_to session.delete(:return_to)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash.notice = 'Post deleted'
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(:content, :photo)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<div class="comment">
  <div id="name-options">
    <%= link_to "#{comment.user.full_name}", user_path(comment.user), class: "comment-author" %>
    <div class="edit-delete">
      <% if comment.user == current_user %>
        <%= link_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "delete" %>
      <% end %>
    </div>
  </div>
  
  <div class="time">
    <%= distance_of_time_in_words(comment.created_at, Time.now) %> ago
  </div>

  <p class="content"><%= comment.content %></p>
</div>

app/views/posts/_form.html.erb
<div id="new-post">
  <%= form_with model: post, local: true do |f| %>
    <%= f.text_area :content, rows: 4, placeholder: "Type here your next post..." %>

    <div class="buttons">
      <div class="photo">
        <%= f.label :photo, 'Upload photo:' %>
        <%= f.file_field :photo %>
      </div>

      <%= f.submit 'Submit', class: "submit" %>
    </div>
  <% end %>
</div>

app/views/posts/_like.html.erb
<div class="likes">
  <div id="count">
    <%= pluralize(post.likes.count, 'like') %>
  </div>
  <% unless current_user.likes.find_by_post_id(post.id) %>
    <%= link_to "Like", post_likes_path(post), method: :post, id: "like" %>
  <% else %>
    <%= link_to "Unlike", post_like_path(post, post.likes.find_by_user_id(current_user)), method: :delete, id: "unlike" %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="post">
  <%= link_to "#{post.user.full_name}", user_path(post.user), class: "post-author" %><br>
  <div class="time">
    <%= distance_of_time_in_words(post.created_at, Time.now) %> ago<br>
  </div>

  <div class="photo-content">
    <% if post.photo.attached? %>
      <%= image_tag post.photo, width: "150", class: "photo" %>
    <% end %>

    <% if post.content %>
      <div class="content">
        <%= post.content %>
      </div>
    <% end %>
  </div>

  <div class="options">
    <%= render partial: 'posts/like', locals: {post: post} %>

    <% if current_user == post.user %>
      <div class="edit-delete">
        <%= link_to "Edit", edit_post_path(post), class: "edit"  %>
        <%= link_to "Delete", post_path(post), method: :delete, data: {confirm: "Remove this post?"}, class: "delete" %>
      </div>
    <% end %>
  </div>

  <div class="comments">
    <% if post.comments.count != 0 %>
      <h4>Comments</h4>
      <%= render partial: 'posts/comment', collection: post.comments %>
    <% end %>
    <%= render partial: 'comments/form', locals: {post: post}%>
  </div>
</div>

app/views/posts/edit.html.erb
<h2>Edit your post</h2>

<%= render partial: 'form', locals: {post: @post} %>

app/views/posts/index.html.erb
<h2><%= current_user.full_name %>'s Timeline</h2>

<%= render partial: 'posts/form', locals: {post: @post} %>

<div class="posts">
  <%= render @posts %>
</div>

app/views/posts/new.html.erb
<h2>Create a post</h2>

<%= render partial: 'form' %>